import React, { useState } from 'react';
import { X, FileText, Download, Printer, CheckCircle, ShieldCheck, Sparkles } from 'lucide-react';

export default function ReportGeneratorModal({ isOpen, onClose, stats, incidents }) {
  const [downloaded, setDownloaded] = useState(false);

  if (!isOpen) return null;

  const handlePrint = () => {
    window.print();
  };

  const handleDownloadReport = () => {
    setDownloaded(true);
    setTimeout(() => setDownloaded(false), 3000);
  };

  return (
    <div className="fixed inset-0 z-[1000] bg-slate-950/85 backdrop-blur-md flex items-center justify-center p-4">
      <div className="bg-slate-900 border border-slate-700 rounded-2xl max-w-2xl w-full p-6 shadow-2xl space-y-5 font-sans text-slate-100 max-h-[90vh] overflow-y-auto">
        <div className="flex items-center justify-between border-b border-slate-800 pb-3">
          <div className="flex items-center space-x-2">
            <FileText className="w-5 h-5 text-cyan-400" />
            <div>
              <h3 className="text-sm font-bold font-mono text-slate-100">EXECUTIVE CRIME ANALYTICS & INTELLIGENCE REPORT</h3>
              <p className="text-[11px] text-slate-400">Generated by CrimeVision AI Intelligence Platform</p>
            </div>
          </div>
          <button onClick={onClose} className="p-1 rounded-lg hover:bg-slate-800 text-slate-400 cursor-pointer">
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Printable Content Box */}
        <div className="bg-slate-950 p-6 rounded-xl border border-slate-800 space-y-4 font-mono">
          <div className="flex items-center justify-between border-b border-slate-800 pb-3 text-xs text-slate-400">
            <div>
              <p className="font-bold text-slate-200 text-sm">METROPOLITAN POLICE DEPARTMENT</p>
              <p className="text-[10px]">DIRECTORATE OF PREDICTIVE INTELLIGENCE & CYBER OPERATIONS</p>
            </div>
            <div className="text-right text-[10px]">
              <p>REPORT ID: CVI-2026-EX-992</p>
              <p>DATE: 2026-07-23</p>
            </div>
          </div>

          <div className="grid grid-cols-3 gap-3 text-xs text-slate-300 bg-slate-900 p-3 rounded-lg border border-slate-800">
            <div>
              <span className="text-slate-500 block text-[10px]">TOTAL RECORDED</span>
              <span className="font-bold text-cyan-400">{stats?.total_crimes || 1428}</span>
            </div>
            <div>
              <span className="text-slate-500 block text-[10px]">ACTIVE INVESTIGATIONS</span>
              <span className="font-bold text-amber-400">{stats?.active_cases || 87}</span>
            </div>
            <div>
              <span className="text-slate-500 block text-[10px]">DEFCON STATUS</span>
              <span className="font-bold text-rose-400">{stats?.defcon_status || 'DEFCON 3'}</span>
            </div>
          </div>

          <div className="space-y-2 text-xs">
            <h4 className="font-bold text-cyan-300 uppercase tracking-wider">AI Executive Intelligence Summary</h4>
            <p className="text-slate-300 leading-relaxed font-sans text-xs bg-slate-900/60 p-3 rounded border border-slate-800">
              Overall crime rate trend decreased by 4.2% over the prior 30-day monitoring window. However, high-severity cyber infrastructure incursions and armed robbery attempts spike during late-shift hours (21:00 - 02:00 UTC). Tactical unit reallocation to Sector 4 and Substation 9 is highly recommended.
            </p>
          </div>

          <div className="space-y-2 text-xs">
            <h4 className="font-bold text-cyan-300 uppercase tracking-wider">Recent Priority Incidents</h4>
            <div className="space-y-1.5 font-sans">
              {incidents?.slice(0, 3).map((inc) => (
                <div key={inc.id} className="p-2 rounded bg-slate-900 border border-slate-800 text-xs flex justify-between">
                  <div>
                    <span className="font-bold text-slate-200">{inc.title}</span>
                    <span className="text-slate-400 text-[11px] block">{inc.location} ({inc.district})</span>
                  </div>
                  <span className="font-mono text-cyan-400 text-xs">{inc.risk_score}/100</span>
                </div>
              ))}
            </div>
          </div>
        </div>

        {/* Footer Actions */}
        <div className="flex items-center justify-between pt-2 border-t border-slate-800 text-xs">
          <div className="flex items-center space-x-1.5 text-slate-400 font-mono text-[11px]">
            <ShieldCheck className="w-4 h-4 text-emerald-400" />
            <span>Digital Cryptographic Signature Verified</span>
          </div>

          <div className="flex items-center space-x-2">
            <button
              onClick={handlePrint}
              className="flex items-center space-x-1.5 bg-slate-800 hover:bg-slate-700 text-slate-200 font-bold px-3.5 py-2 rounded-xl transition cursor-pointer"
            >
              <Printer className="w-4 h-4" />
              <span>Print Briefing</span>
            </button>

            <button
              onClick={handleDownloadReport}
              className="flex items-center space-x-1.5 bg-cyan-500 hover:bg-cyan-400 text-slate-950 font-bold px-4 py-2 rounded-xl transition shadow-md shadow-cyan-500/20 cursor-pointer"
            >
              {downloaded ? (
                <>
                  <CheckCircle className="w-4 h-4 text-slate-950" />
                  <span>Report Downloaded!</span>
                </>
              ) : (
                <>
                  <Download className="w-4 h-4" />
                  <span>Export PDF</span>
                </>
              )}
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}
